/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lookfeel;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Samuel
 */
public class LookFeel extends javax.swing.JFrame {

    /**
     * Creates new form LookFeel
     */
    public LookFeel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5", "Item 6", "Item 7", "Item 8", "Item 9" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList2);

        jButton1.setText("jButton1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(171, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(167, 167, 167))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(42, 42, 42))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(148, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
             try {
                JFrame.setDefaultLookAndFeelDecorated(true);

               //UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());//La que controla, pone una especie de filtro.
              UIManager.setLookAndFeel("javax.swing.plaf.metal.MetalLookAndFeel");
               } catch (ClassNotFoundException ex) {
                Logger.getLogger(LookFeel.class.getName()).log(Level.SEVERE, null,
               ex);
                } catch (InstantiationException ex) {
                Logger.getLogger(LookFeel.class.getName()).log(Level.SEVERE, null,
               ex);
                } catch (IllegalAccessException ex) {
                Logger.getLogger(LookFeel.class.getName()).log(Level.SEVERE, null,
               ex);
                } catch (UnsupportedLookAndFeelException ex) {
                Logger.getLogger(LookFeel.class.getName()).log(Level.SEVERE, null,
               ex);
                }

//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info :
//           javax.swing.UIManager.getInstalledLookAndFeels()) {
//            if ("Nimbus".equals(info.getName())) {
//            javax.swing.UIManager.setLookAndFeel(info.getClassName());
//            break;
//            }
//            }
//            
//            } catch (ClassNotFoundException ex) {
//
//           java.util.logging.Logger.getLogger(LookFeel.class.getName()).log(java.util.logging.
//           Level.SEVERE, null, ex);
//            } catch (InstantiationException ex) {
//
//           java.util.logging.Logger.getLogger(LookFeel.class.getName()).log(java.util.logging.
//           Level.SEVERE, null, ex);
//            } catch (IllegalAccessException ex) {
//
//           java.util.logging.Logger.getLogger(LookFeel.class.getName()).log(java.util.logging.
//           Level.SEVERE, null, ex);
//            } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//
//           java.util.logging.Logger.getLogger(LookFeel.class.getName()).log(java.util.logging.
//           Level.SEVERE, null, ex);
//            }

        java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
        new LookFeel().setVisible(true);
        }
        });
        }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
