/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Prueba;

import static Prueba.MetodosCalculadora.pulsaIgual;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author alumno
 */
public class Calculadora extends javax.swing.JFrame {
    public String estado="";//Variable auxiliar que va informando de la operación que se está realizando en la calculadora.
    public String operacion="";//Varibale auxiliar que va almacenando los operandos y la operación.
    /**
     * Creates new form Calculadora
     */
    public Calculadora() {
        initComponents();
        /*
            Deshabilitamos los botones que realizan operaciones desde el principio.
        */
        jButtonSuma.setEnabled(false);
        jButtonResta.setEnabled(false);
        jButtonMultiplicacion.setEnabled(false);
        jButtonDivision.setEnabled(false);
        jButtonResultado.setEnabled(false);
        jButton0.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton0 = new javax.swing.JButton();
        jButtonBorrar = new javax.swing.JButton();
        jButtonResultado = new javax.swing.JButton();
        jButtonSuma = new javax.swing.JButton();
        jButtonResta = new javax.swing.JButton();
        jButtonDivision = new javax.swing.JButton();
        jButtonMultiplicacion = new javax.swing.JButton();
        jLabelresultado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setText("2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 60, 40));

        jButton1.setText("1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 62, 60, 40));

        jButton3.setText("3");
        jButton3.setToolTipText("");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 60, 40));

        jButton4.setText("4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 60, 40));

        jButton5.setText("5");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 60, 40));

        jButton6.setText("6");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 60, 40));

        jButton7.setText("7");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 60, 40));

        jButton8.setText("8");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 60, 40));

        jButton9.setText("9");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 60, 40));

        jButton0.setText("0");
        jButton0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton0ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton0, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 60, 40));

        jButtonBorrar.setText("C");
        jButtonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 60, 40));

        jButtonResultado.setText("=");
        jButtonResultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResultadoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 60, 40));

        jButtonSuma.setText("+");
        jButtonSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSumaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSuma, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, 60, 40));

        jButtonResta.setText("-");
        jButtonResta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRestaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonResta, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, 60, 40));

        jButtonDivision.setText("/");
        jButtonDivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDivisionActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonDivision, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, 60, 40));

        jButtonMultiplicacion.setText("x");
        jButtonMultiplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMultiplicacionActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonMultiplicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, 60, 40));

        jLabelresultado.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelresultado.setText("0");
        jLabelresultado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabelresultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 320, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //Si se pulsa el botón "1":
        if(!estado.equals(""))
        {
            habilitarOperaciones(jButtonResultado);//Habilitamos el botón '='.
            habilitarOperaciones(jButton0);//Habilitamos también el botón 0.
        }
        else
        {
            habilitarOperaciones(jButtonSuma, jButtonResta, jButtonMultiplicacion, jButtonDivision, jButton0);//Habilitamos los botones para realizar operaciones excepto el '=', y el 0.
        }
        if(jLabelresultado.getText().equals("0"))//Si el JLabel tiene únicamente el valor "0", lo vacía.
        {
            jLabelresultado.setText("");
        }
        jLabelresultado.setText(jLabelresultado.getText()+"1");//Se sustituye lo que contiene la etiqueta.
        operacion=operacion+1;//Si el estado de la operación cumple los requisitos, se añadirá el valor "1" al String "operacion".
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSumaActionPerformed
        //Si se pulsa el botón "+".
        deshabilitarOperaciones(jButtonSuma, jButtonResta, jButtonMultiplicacion, jButtonDivision, jButtonResultado);//Deshabilitamos todos botones de operación.
        estado="sumando";//Cambia el estado.
        operacion=operacion+"+";//Añade "+" al String "operacion".
        jLabelresultado.setText("");//Se vacía el contenido del JLabel.
        deshabilitarOperaciones(jButton0);
    }//GEN-LAST:event_jButtonSumaActionPerformed

    private void jButtonRestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRestaActionPerformed
        //Si se pulsa el botón "-".
        deshabilitarOperaciones(jButtonSuma, jButtonResta, jButtonMultiplicacion, jButtonDivision, jButtonResultado);//Deshabilitamos todos botones de operación.
        estado="restando";//Cambia el estado.
        operacion=operacion+"-";//Añade "-" al String "operacion".
        jLabelresultado.setText("");//Se vacía el contenido del JLabel.
        deshabilitarOperaciones(jButton0);
    }//GEN-LAST:event_jButtonRestaActionPerformed

    private void jButtonMultiplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMultiplicacionActionPerformed
        //Si se pulsa el botón "x".
        deshabilitarOperaciones(jButtonSuma, jButtonResta, jButtonMultiplicacion, jButtonDivision, jButtonResultado);//Deshabilitamos todos botones de operación.
        estado="multiplicando";//Cambia el estado.
        operacion=operacion+"x";//Añade "x" al String "operacion".
        jLabelresultado.setText("");//Se vacía el contenido del JLabel.
        deshabilitarOperaciones(jButton0);
    }//GEN-LAST:event_jButtonMultiplicacionActionPerformed

    private void jButtonDivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDivisionActionPerformed
        //Si se pulsa el botón "/".
        deshabilitarOperaciones(jButtonSuma, jButtonResta, jButtonMultiplicacion, jButtonDivision, jButtonResultado);//Deshabilitamos todos botones de operación.
        estado="dividiendo";//Cambia el estado.
        operacion=operacion+"/";//Añade "/" al String "operacion".
        jLabelresultado.setText("");//Se vacía el contenido del JLabel.
        deshabilitarOperaciones(jButton0);
    }//GEN-LAST:event_jButtonDivisionActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //Si se pulsa el botón "2":
        if(!estado.equals(""))
        {
            habilitarOperaciones(jButtonResultado);//Habilitamos el botón '='.
            habilitarOperaciones(jButton0);//Habilitamos también el botón 0.
        }
        else
        {
            habilitarOperaciones(jButtonSuma, jButtonResta, jButtonMultiplicacion, jButtonDivision, jButton0);//Habilitamos los botones para realizar operaciones excepto el '=', y el 0.
        }
        if(jLabelresultado.getText().equals("0"))//Si el JLabel tiene únicamente el valor "0", lo vacía.
        {
            jLabelresultado.setText("");
        }
        jLabelresultado.setText(jLabelresultado.getText()+"2");//Si el estado de la operación cumple los requisitos, se añadirá el valor "2" al String que contiene la etiqueta.
        operacion=operacion+2;//Si el estado de la operación cumple los requisitos, se añadirá el valor "1" al String "operacion".
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       //Si se pulsa el botón "3":
        if(!estado.equals(""))
        {
            habilitarOperaciones(jButtonResultado);//Habilitamos el botón '='.
            habilitarOperaciones(jButton0);//Habilitamos también el botón 0.
        }
        else
        {
            habilitarOperaciones(jButtonSuma, jButtonResta, jButtonMultiplicacion, jButtonDivision, jButton0);//Habilitamos los botones para realizar operaciones excepto el '=', y el 0.
        }
        if(jLabelresultado.getText().equals("0"))//Si el JLabel tiene únicamente el valor "0", lo vacía.
        {
            jLabelresultado.setText("");
        }
        jLabelresultado.setText(jLabelresultado.getText()+"3");//Si el estado de la operación cumple los requisitos, se añadirá el valor "3" al String que contiene la etiqueta.
        operacion=operacion+3;//Si el estado de la operación cumple los requisitos, se añadirá el valor "1" al String "operacion".
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        //Si se pulsa el botón "4":
        if(!estado.equals(""))
        {
             habilitarOperaciones(jButtonResultado);//Habilitamos el botón '='.
            habilitarOperaciones(jButton0);//Habilitamos también el botón 0.
        }
        else
        {
            habilitarOperaciones(jButtonSuma, jButtonResta, jButtonMultiplicacion, jButtonDivision, jButton0);//Habilitamos los botones para realizar operaciones excepto el '=', y el 0.
        }
        if(jLabelresultado.getText().equals("0"))//Si el JLabel tiene únicamente el valor "0", lo vacía.
        {
            jLabelresultado.setText("");
        }
        jLabelresultado.setText(jLabelresultado.getText()+"4");//Si el estado de la operación cumple los requisitos, se añadirá el valor "4" al String que contiene la etiqueta.
        operacion=operacion+4;//Si el estado de la operación cumple los requisitos, se añadirá el valor "1" al String "operacion".
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        //Si se pulsa el botón "5":
        if(!estado.equals(""))
        {
             habilitarOperaciones(jButtonResultado);//Habilitamos el botón '='.
            habilitarOperaciones(jButton0);//Habilitamos también el botón 0.
        }
        else
        {
            habilitarOperaciones(jButtonSuma, jButtonResta, jButtonMultiplicacion, jButtonDivision, jButton0);//Habilitamos los botones para realizar operaciones excepto el '=', y el 0.
        }
        if(jLabelresultado.getText().equals("0"))//Si el JLabel tiene únicamente el valor "0", lo vacía.
        {
            jLabelresultado.setText("");
        }
        jLabelresultado.setText(jLabelresultado.getText()+"5");//Si el estado de la operación cumple los requisitos, se añadirá el valor "5" al String que contiene la etiqueta.
        operacion=operacion+5;//Si el estado de la operación cumple los requisitos, se añadirá el valor "1" al String "operacion".
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        //Si se pulsa el botón "6":
        if(!estado.equals(""))
        {
             habilitarOperaciones(jButtonResultado);//Habilitamos el botón '='.
            habilitarOperaciones(jButton0);//Habilitamos también el botón 0.
        }
        else
        {
            habilitarOperaciones(jButtonSuma, jButtonResta, jButtonMultiplicacion, jButtonDivision, jButton0);//Habilitamos los botones para realizar operaciones excepto el '=', y el 0.
        }
        if(jLabelresultado.getText().equals("0"))//Si el JLabel tiene únicamente el valor "0", lo vacía.
        {
            jLabelresultado.setText("");
        }
        jLabelresultado.setText(jLabelresultado.getText()+"6");//Si el estado de la operación cumple los requisitos, se añadirá el valor "6" al String que contiene la etiqueta.
        operacion=operacion+6;//Si el estado de la operación cumple los requisitos, se añadirá el valor "1" al String "operacion".
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        //Si se pulsa el botón "7":
        if(!estado.equals(""))
        {
             habilitarOperaciones(jButtonResultado);//Habilitamos el botón '='.
            habilitarOperaciones(jButton0);//Habilitamos también el botón 0.
        }
        else
        {
            habilitarOperaciones(jButtonSuma, jButtonResta, jButtonMultiplicacion, jButtonDivision, jButton0);//Habilitamos los botones para realizar operaciones excepto el '=', y el 0.
        }
        if(jLabelresultado.getText().equals("0"))//Si el JLabel tiene únicamente el valor "0", lo vacía.
        {
            jLabelresultado.setText("");
        }
        jLabelresultado.setText(jLabelresultado.getText()+"7");//Si el estado de la operación cumple los requisitos, se añadirá el valor "7" al String que contiene la etiqueta.
        operacion=operacion+7;//Si el estado de la operación cumple los requisitos, se añadirá el valor "1" al String "operacion".
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        //Si se pulsa el botón "8":
        if(!estado.equals(""))
        {
             habilitarOperaciones(jButtonResultado);//Habilitamos el botón '='.
            habilitarOperaciones(jButton0);//Habilitamos también el botón 0.
        }
        else
        {
            habilitarOperaciones(jButtonSuma, jButtonResta, jButtonMultiplicacion, jButtonDivision, jButton0);//Habilitamos los botones para realizar operaciones excepto el '=', y el 0.
        }
        if(jLabelresultado.getText().equals("0"))//Si el JLabel tiene únicamente el valor "0", lo vacía.
        {
            jLabelresultado.setText("");
        }
        jLabelresultado.setText(jLabelresultado.getText()+"8");//Si el estado de la operación cumple los requisitos, se añadirá el valor "8" al String que contiene la etiqueta.
        operacion=operacion+8;//Si el estado de la operación cumple los requisitos, se añadirá el valor "1" al String "operacion".
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
       //Si se pulsa el botón "9":
        if(!estado.equals(""))
        {
             habilitarOperaciones(jButtonResultado);//Habilitamos el botón '='.
            habilitarOperaciones(jButton0);//Habilitamos también el botón 0.
        }
        else
        {
            habilitarOperaciones(jButtonSuma, jButtonResta, jButtonMultiplicacion, jButtonDivision, jButton0);//Habilitamos los botones para realizar operaciones excepto el '=', y el 0.
        }
        if(jLabelresultado.getText().equals("0"))//Si el JLabel tiene únicamente el valor "0", lo vacía.
        {
            jLabelresultado.setText("");
        }
        jLabelresultado.setText(jLabelresultado.getText()+"9");//Si el estado de la operación cumple los requisitos, se añadirá el valor "9" al String que contiene la etiqueta.
        operacion=operacion+9;//Si el estado de la operación cumple los requisitos, se añadirá el valor "1" al String "operacion".
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton0ActionPerformed
        //Si se pulsa el botón "0":
        jLabelresultado.setText(jLabelresultado.getText()+"0");//Si el estado de la operación cumple los requisitos, se añadirá el valor "0" al String que contiene la etiqueta.
        operacion=operacion+0;//Si el estado de la operación cumple los requisitos, se añadirá el valor "1" al String "operacion".
    }//GEN-LAST:event_jButton0ActionPerformed

    private void jButtonResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResultadoActionPerformed
        //Si se pulsa el botón "=".
        try {
            jLabelresultado.setText(pulsaIgual(operacion,estado));//Llama al método "pulsaIgual" en MetodosCalculadora.java.
            estado="terminado";
        /*
            Deshabilitamos todos los botones.
        */
        deshabilitarOperaciones(jButtonSuma, jButtonResta, jButtonMultiplicacion, jButtonDivision, jButtonResultado);
        deshabilitarOperaciones(jButton0, jButton1, jButton2, jButton3, jButton4);
        deshabilitarOperaciones(jButton5, jButton6, jButton7, jButton8, jButton9);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane,ex.getMessage());//Si recibe una excepción muestra el mensaje inherente a ella.
        }
    }//GEN-LAST:event_jButtonResultadoActionPerformed

    private void jButtonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarActionPerformed
        //Si se pulsa "C".
        jLabelresultado.setText("0");//Reinicia el resultado a estar vacío.
        estado="";//Reinicia el estado a uno modificable por los distintos signos.
        operacion="";
        /*
            Deshabilitamos todos los botones necesarios para el estado inicial.
        */
        deshabilitarOperaciones(jButtonSuma, jButtonResta, jButtonMultiplicacion, jButtonDivision, jButtonResultado);
        deshabilitarOperaciones(jButton0);
        habilitarOperaciones(jButton4, jButton1, jButton2, jButton3, null);
        habilitarOperaciones(jButton5, jButton6, jButton7, jButton8, jButton9);
    }//GEN-LAST:event_jButtonBorrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton0;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButtonBorrar;
    private javax.swing.JButton jButtonDivision;
    private javax.swing.JButton jButtonMultiplicacion;
    private javax.swing.JButton jButtonResta;
    private javax.swing.JButton jButtonResultado;
    private javax.swing.JButton jButtonSuma;
    private javax.swing.JLabel jLabelresultado;
    // End of variables declaration//GEN-END:variables
    
public static void habilitarOperaciones(JButton a, JButton b, JButton c, JButton d, JButton e)//Método que habilita 5 JButton que se le pasen como parámetro.
{
    a.setEnabled(true);
    b.setEnabled(true);
    c.setEnabled(true);
    d.setEnabled(true);
    if(e!=null)
    e.setEnabled(true);
}

public static void deshabilitarOperaciones(JButton a, JButton b, JButton c, JButton d, JButton e)//Método que deshabilita 5 JButton que se le pasen como parámetro.
{
    a.setEnabled(false);
    b.setEnabled(false);
    c.setEnabled(false);
    d.setEnabled(false);
    e.setEnabled(false);
}

public static void deshabilitarOperaciones(JButton a)
{
    a.setEnabled(false);
}

public static void habilitarOperaciones(JButton a)
{
    a.setEnabled(true);
}

}
